### ISSUE TITLE
Wrap encrypted text

### ISSUE THREAD

**Issue by JeffMill** [jamesbachini/Encryption-VScode#1]
Currently the extension creates one really long line, e.g.

`
U2FsdGVkX1+zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/tVn1SVLX5fa7K
`

would be nice (especially for emailing) if the encryption split (i.e. insert CR or CRLF) the line at VSCode's "Word Wrap Column" setting, so if I have that set as 80, I'd see:

`
U2FsdGVkX1+zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/tVn1SVLX5fa7K
`

Of course, the decrypt function would remove CR and LF before attempting decryption.

**Comment by jamesbachini** [comment]
Hi Jeff,

Nice to see the plugin is getting used, thanks for the suggestion. I've done an update for this which should get pushed out automatically eventually. Basically adding "\r\n" at intervals of the wordWrapColumn setting.

Commit:
https://github.com/jamesbachini/Encryption-VScode/commit/4868ae6ff1527cedb7a1cad4347d5b583fb65ce7

Update is live at:
https://marketplace.visualstudio.com/items?itemName=JamesBachini.encryption-vscode
