### ISSUE TITLE
Breaks with too long passphrases

### ISSUE THREAD

**Issue by DrDBanner** [jamesbachini/Encryption-VScode#4]
### Passphrase
Q47fc41b753cba8c1aacd8d6d47f925da30cfc420115b08083a6267154fad321

### Test video
![b033912ff10e77a7ce0c22b482e541b2](https://user-images.githubusercontent.com/25568865/94285248-b9a22080-ff53-11ea-9f66-79cd414de4c1.gif)

**Comment by jamesbachini** [comment]
Must be a limitation of the encryption used which uses the crypto-js npm module.
