### ISSUE TITLE
File content gets deleted after decrypt

### ISSUE THREAD

**Issue by netisfree** [jamesbachini/Encryption-VScode#5]
File content gets deleted from the file after enter the decryption passphrase correctly.

**Comment by Dowwie** [comment]
@netisfree :  select all, encrypt.   select all, decrypt.

**Comment by taureanamir** [comment]
Facing the same issue

**Comment by jamesbachini** [comment]
Can you recreate it with a test document? The contents go blank if the passphrase is incorrect, so double check that too.
