### ISSUE TITLE
Error "Malformed UTF-8 data"

### ISSUE THREAD

**Issue by zerg-su** [jamesbachini/Encryption-VScode#6]
I have problem with encrypt/decrypt my files. When I try do that I see next message:
![image](https://user-images.githubusercontent.com/65297783/104576436-3c68fb80-5669-11eb-9d44-b21f86b9edb6.png)

For example I encrypted file but I can't decrypt them.

**Comment by jamesbachini** [comment]
Any unusual characters in the text document? check the password too.
